proxy:
# - type: in # in: 인바운드, out: 아웃바운드
#   name: sample-1 # 프록시의 이름
#   bindPort: 8080 # 바인드할 포트
#   forwardHost: 10.1.3.200 # 전달할 서버의 아이피
#   forwardPort: 21 # 전달할 서버의 포트
#   allowedCountries: [private, localhost] # 국가코드: KR, JP 등등.., private: 내부망, localhost: 루프백, Any: 아무나
  - type: in
    name: sample-1
    bindPort: 8081
    forwardHost: 10.1.3.130
    forwardPort: 30500
    allowedCountries: [private]
  - type: out
    name: sample-2
    bindPort: 8082
    forwardHost: 10.1.3.130
    forwardPort: 31500
    allowedCountries: [Any]